spring.application.name=api.rinha.v2
spring.datasource.url=jdbc:postgresql://localhost:5434/api_rinha_v2
spring.datasource.username=postgres
spring.datasource.password=loucurapura22
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=always

api.security.token.secret=${JWT_SECRET:12345678}

mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.test.token=${MERCADOPAGO_TEST_TOKEN}

#Emitir Pagamento URL Notification
#mercadopago.notification.url=${MERCADOPAGO_NOTIFICATION_URL}


logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
