# ============================================================
#  Overrides para profile dev
# ============================================================

# SQL no console (debug de queries)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Stacktrace completo em respostas de erro - facilita debug local.
spring.web.error.include-stacktrace=always

# Logs verbosos de seguranca
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG
