spring.application.name=api.rinha.v2
spring.datasource.url=jdbc:postgresql:${POSTGRES_RINHA_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#log da operação no banco de dados para debug
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktrace=always

api.security.token.secret=${JWT_SECRET:12345678}

mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.test.token=${MERCADOPAGO_TEST_TOKEN}

imgur.access.token=${IMGUR_ACCESS_TOKEN}

#Emitir Pagamento URL Notification
#mercadopago.notification.url=${MERCADOPAGO_NOTIFICATION_URL}


#Logs para debug
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.security.web.authentication=DEBUG


#Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ??? URL do Frontend (usada no link do email)
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
