# ============================================================
#  Overrides para profile prod
# ============================================================

# Sem SQL no log.
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logs em nivel sano.
logging.level.root=INFO
logging.level.org.springframework.security=WARN

# Desabilita Swagger / OpenAPI publico em prod (hardening).
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
